{% set version = "7.2.7" %}

package:
  name: virtuoso-opensource
  version: {{ version }}

source:
  url: https://github.com/openlink/virtuoso-opensource/archive/v{{ version }}.tar.gz
  sha256: 5e3f68fe43030dfcec461211ae4401620009b872f70abad061a90c0b9cefb2f0

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf <=2.69 # [unix]
    - automake <=1.16.1  # [unix]
    - libtool <=2.4.6 # [unix]
    - flex <=2.6.4  # [unix]
    - bison <=3.5.1 # [unix]
    - gperf <=3.1 # [unix]
    - gawk <=3.1.1 # [unix]
    - m4 <=1.4.18  # [unix]
    - make <=4.2.1 # [unix]
  host:
    - openssl
  run:
    - openssl


test:
  commands:
    # virtuoso-t, isql, isqlw, virt_mail, virtuoso-sample-t, inifile
    - isql --help

about:
  home: https://virtuoso.openlinksw.com
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: |
    Virtuoso is a high-performance and scalable Multi-Model RDBMS, Data
    Integration Middleware, Linked Data Deployment, and HTTP Application Server
    Platform
  doc_url: http://vos.openlinksw.com/owiki/wiki/VOS
  dev_url: https://github.com/openlink/virtuoso-opensource

extra:
  recipe-maintainers:
    - bollwyvl
