travis:
  secure:
    BINSTAR_TOKEN: UhR7WRR6MO45HKJNyS+APDMYNO7M426XuRWLPpEPGgafyN3+ZkEOkV0fwVFZ5Gi0qU5Ag5fh0XY2attxgLrAmUMcQb5A/yTPTXGT18oO0sWS0f8THxmk5j7uPxMZ/vkRue3a4dyGCATorP5JNh/HxJ33OSrTOEHtNfqaOnnNjH3ajCfjFtkVd45nhnyXUqLOzZsGXc2rypTGJAIuBnIMHiXkoWd4/GSTqPoBN9xcA65UXtCHl92LBCo3Dgf3m+rU3SfmnRCQGPWernQzDi/hZTvuIkDdIjbG3m5iDu5+f6RX/OhnuloCm40pTdqc6jo/0sS5D7T2M0A/3uqftriOzZgVb+N15nUASh3rqWv2Q7JGNIhs3AL0Gwcy8Fc8wbleCVaYU5L/Kov9BEu2MH4ZMH0jJppVYZ0400h85ihEfj49s2DDSKfH3WAJPH8XgTjJGvoZ70AgY4+Re32otx1bpO952f5HJwARA0Y499Jo+nWyfUvvwFCDT9uTCAEnJlmeqhm0EqXw30tDJad2d8hRwS+5hGUjHMl0AR/tIOV8W+lyeUkB3LZR6I9uBn9WfMgZRDmzoddK3ZjpnIdde24sqc0DQp4bCFn+KoeCeaWr/A6o/jANJ0QBMrLKeczqH0tZLN1POsszkVPiveZpqIPOb10jFRWs8gpi3NxoMBn6e9U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
